/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webcanvas_free: (a: number, b: number) => void;
export const webcanvas_beginStroke: (a: number, b: number, c: number, d: number, e: number) => number;
export const webcanvas_clear: (a: number) => number;
export const webcanvas_create: (a: any, b: number, c: number, d: number, e: number) => any;
export const webcanvas_endStroke: (a: number) => number;
export const webcanvas_loadDocument: (a: number, b: any) => [number, number];
export const webcanvas_panBy: (a: number, b: number, c: number) => number;
export const webcanvas_pushStrokeSamples: (a: number, b: number, c: number) => number;
export const webcanvas_redo: (a: number) => number;
export const webcanvas_render: (a: number) => number;
export const webcanvas_resize: (a: number, b: number, c: number, d: number) => void;
export const webcanvas_saveDocument: (a: number) => [number, number, number];
export const webcanvas_setBrushSize: (a: number, b: number) => void;
export const webcanvas_setColor: (a: number, b: number, c: number, d: number) => void;
export const webcanvas_setTool: (a: number, b: number) => [number, number];
export const webcanvas_setWorkspaceDarkMode: (a: number, b: number) => void;
export const webcanvas_undo: (a: number) => number;
export const webcanvas_zoomAt: (a: number, b: number, c: number, d: number) => number;
export const wasm_bindgen__convert__closures_____invoke__h3c9d997bc3177e87: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h44b72ec416254d87: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5b4127e1602774fb: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
